/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeAll;

class AppTest {
    private static App app;

    @BeforeAll
    public static void setUp() {
        AppTest.app = new App();
    }

    @Test
    public void testObjectCretion() {
        assertNotNull(app);
    }

}
